spring:
  profiles.active: local
---
spring:
  config:
    activate:
      on-profile: local
  cache:
    type: redis
  flyway:
    enabled: false
  datasource:
    url: jdbc:mariadb://localhost:13306/tickets?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root!@#
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379

logging:
  level:
    org.hibernate.sql: debug